version: '3.8'

services:
  db:
    container_name: postgre_db5
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    container_name: fastapi_app
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


