"""базовая миграция 1

Revision ID: fc95c03585f8
Revises: 
Create Date: 2024-11-19 16:05:04.469667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc95c03585f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_rates_cargo_type'), 'cargo_rates', ['cargo_type'], unique=False)
    op.create_index(op.f('ix_cargo_rates_id'), 'cargo_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_rates_id'), table_name='cargo_rates')
    op.drop_index(op.f('ix_cargo_rates_cargo_type'), table_name='cargo_rates')
    op.drop_table('cargo_rates')
    # ### end Alembic commands ###
